# Generated by Django 4.1 on 2024-01-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('type', models.CharField(max_length=255, verbose_name='종류')),
                ('desc', models.TextField(max_length=5000, verbose_name='개발툴 설명')),
            ],
        ),
    ]
